

services:
  chroma:
    container_name: chroma
    hostname: chroma
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
      - ./.local/chroma:/chroma/chroma/
    ports:
      - 8099:8000
