

services:
  redisvector:
    container_name: redisvector
    hostname: redisvector
    image: redislabs/redisearch:2.8.8
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redisvector:6379
    ports:
      - "8087:8081"
