version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 8093:11434
    volumes:
      - ./.local/ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8G
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./.local/ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8094:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    restart: unless-stopped
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8081'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.10
    ports:
      - 8091:8081
      - 50051:50051
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'admin,user'
      AUTHENTICATION_APIKEY_USERS: 'admin,user'
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'
      AUTHORIZATION_ADMINLIST_USERS: 'admin'
      AUTHORIZATION_ADMINLIST_READONLY_USERS: 'user'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - './.local/weaviate:/var/lib/weaviate'
    healthcheck:
      test: [ "CMD", "curl", "-s", "-f", "http://localhost:8080/v1/.well-known/ready" ]
      interval: 10s
      timeout: 10s
      retries: 5
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.7.3
    ports:
      - "8092:6333"
      - "6334:6334"
    volumes:
      - ./.local/qdrant/qdrant_storage:/qdrant/storage