services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 8093:11434
    volumes:
      - ./.local/ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 8G
