version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 8093:11434
    volumes:
      - ./.local/ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8G
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./.local/ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8094:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    restart: unless-stopped