version: '3'

services:
  pgvector:
    container_name: pgvector
    image:  pgvector/pgvector:pg16
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./.local/postgresql/data:/var/lib/postgresql/data